version: "3.9"

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python_api-finance
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null
    restart: unless-stopped

